# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b07d4228b2c8104fe26245028b2f2de4857444631a8604e381f6ed8f5f2f8677eafa752ab3318488ef1ee941ad91cdcb61f1f05c363c727802f6edde34ec857

test:
  secret_key_base: 3a3ea02348c351330004a9a13e47688221c5a10a0cbc9e380ff4c2c22a36c7da1e862002e728bacbee7c38d532faab735bf2297d2f0044597f354956e5fffc4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
